# Disable Elasticsearch references completely
elasticsearch:
  enabled: false

# Disable Kibana references
kibana:
  enabled: false

# Configure Filebeat
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      # Filter namespaces starting with "cicd" or "student"
      include_namespaces: ["cicd*", "student*"]

    processors:
      - add_host_metadata: ~
      # Add namespace filtering processor
      - drop_event:
          when:
            not:
              or:
                - regexp:
                    kubernetes.namespace: "^cicd"
                - regexp:
                    kubernetes.namespace: "^student"

    # Send to Logstash
    output.logstash:
      hosts: [ "http://logstash-logstash.logging:5044" ]

# Minimal resources
resources:
  requests:
    cpu: "50m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "200Mi"

# Deploy as DaemonSet to collect logs from all nodes
daemonset:
  enabled: true
  
deployment:
  enabled: false

# Disable node affinity
nodeSelector: {}
affinity: {}
tolerations: []

ssl:
  enabled: false

secretMounts: []
