apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-app-deployment
    namespace: cicd-pipeline-alpha
    labels:
        app: go-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-app
    template:
        metadata:
            labels:
                app: go-app
        spec:
            containers:
                - name: go-app
                  image: asia-southeast1-docker.pkg.dev/devops-docker-demo-458213/week7/go-app:REPLACE_IMAGE_TAG
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  resources:
                      limits:
                          cpu: "500m"
                          memory: "512Mi"
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
    name: go-app-service
    namespace: cicd-pipeline-alpha
    labels:
        app: go-app
spec:
    selector:
        app: go-app
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
    type: ClusterIP
