# fluent-bit-values.yaml
image:
  repository: fluent/fluent-bit
  tag: 2.1.10
  pullPolicy: IfNotPresent

# Minimal resources
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

# Deploy as DaemonSet to collect logs from all nodes
daemonset:
  enabled: true

# Configure Fluent Bit
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*student*.log,/var/log/containers/*cicd*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name forward
        Match *
        Host logstash-logstash.logging.svc.cluster.local
        Port 5170
        tls Off

  parsers: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

# Disable persistence
persistence:
  enabled: false

# Disable metrics
metrics:
  enabled: false

# Tolerate all nodes
tolerations:
- operator: Exists
